// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LandErp.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class KanbanPipelines : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddUniqueConstraint(
                name: "ak_property_cases_organization_id_id",
                schema: "procurement",
                table: "property_cases",
                columns: new[] { "organization_id", "id" });

            migrationBuilder.CreateTable(
                name: "kanban_pipelines",
                schema: "procurement",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Канбан: Id. Исторические факты не удаляются."),
                    organization_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Организация-владелец записи; граница изоляции доступа, устанавливаемая сервером."),
                    name = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: false, comment: "Канбан: Name. Исторические факты не удаляются."),
                    sort_order = table.Column<int>(type: "integer", nullable: false, comment: "Канбан: SortOrder. Исторические факты не удаляются."),
                    is_default = table.Column<bool>(type: "boolean", nullable: false, comment: "Канбан: IsDefault. Исторические факты не удаляются."),
                    is_active = table.Column<bool>(type: "boolean", nullable: false, comment: "Канбан: IsActive. Исторические факты не удаляются."),
                    version = table.Column<long>(type: "bigint", nullable: false, comment: "Версия для optimistic concurrency. Каждое изменение увеличивает значение; stale commands отклоняются.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_kanban_pipelines", x => x.id);
                    table.UniqueConstraint("ak_kanban_pipelines_organization_id_id", x => new { x.organization_id, x.id });
                    table.CheckConstraint("ck_kanban_pipeline_name", "length(btrim(name)) > 0");
                    table.ForeignKey(
                        name: "fk_kanban_pipelines_organization_id",
                        column: x => x.organization_id,
                        principalSchema: "organization",
                        principalTable: "organizations",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                },
                comment: "Воронки организации; пользовательские стадии независимы от бизнес-решений.");

            migrationBuilder.CreateTable(
                name: "kanban_stages",
                schema: "procurement",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Канбан: Id. Исторические факты не удаляются."),
                    organization_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Организация-владелец записи; граница изоляции доступа, устанавливаемая сервером."),
                    pipeline_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Канбан: PipelineId. Исторические факты не удаляются."),
                    name = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: false, comment: "Канбан: Name. Исторические факты не удаляются."),
                    description = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: false, comment: "Канбан: Description. Исторические факты не удаляются."),
                    color_key = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false, comment: "Канбан: ColorKey. Исторические факты не удаляются."),
                    sort_order = table.Column<int>(type: "integer", nullable: false, comment: "Канбан: SortOrder. Исторические факты не удаляются."),
                    is_initial = table.Column<bool>(type: "boolean", nullable: false, comment: "Канбан: IsInitial. Исторические факты не удаляются."),
                    kind = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false, comment: "Канбан: Kind. Исторические факты не удаляются."),
                    is_active = table.Column<bool>(type: "boolean", nullable: false, comment: "Канбан: IsActive. Исторические факты не удаляются."),
                    is_hidden_on_board = table.Column<bool>(type: "boolean", nullable: false, comment: "Канбан: IsHiddenOnBoard. Исторические факты не удаляются."),
                    version = table.Column<long>(type: "bigint", nullable: false, comment: "Версия для optimistic concurrency. Каждое изменение увеличивает значение; stale commands отклоняются.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_kanban_stages", x => x.id);
                    table.UniqueConstraint("ak_kanban_stages_organization_id_id", x => new { x.organization_id, x.id });
                    table.UniqueConstraint("ak_kanban_stages_organization_id_pipeline_id_id", x => new { x.organization_id, x.pipeline_id, x.id });
                    table.CheckConstraint("ck_kanban_stage_initial", "NOT is_initial OR (is_active AND kind = 'Working')");
                    table.CheckConstraint("ck_kanban_stage_name", "length(btrim(name)) > 0");
                    table.ForeignKey(
                        name: "fk_kanban_stages_organization_id_pipeline_id",
                        columns: x => new { x.organization_id, x.pipeline_id },
                        principalSchema: "procurement",
                        principalTable: "kanban_pipelines",
                        principalColumns: new[] { "organization_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                },
                comment: "Пользовательские стадии: порядок и видимость общие для воронки.");

            migrationBuilder.CreateTable(
                name: "kanban_memberships",
                schema: "procurement",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Канбан: Id. Исторические факты не удаляются."),
                    organization_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Организация-владелец записи; граница изоляции доступа, устанавливаемая сервером."),
                    property_case_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Самостоятельный рабочий объект закупки, к которому относится источник."),
                    pipeline_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Канбан: PipelineId. Исторические факты не удаляются."),
                    stage_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Текущая стадия закупки. Только acquired обозначает подтверждённую завершённую покупку."),
                    stage_entered_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "Канбан: StageEnteredAt. Исторические факты не удаляются."),
                    stage_exited_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "Канбан: StageExitedAt. Исторические факты не удаляются."),
                    joined_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "Канбан: JoinedAt. Исторические факты не удаляются."),
                    transferred_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true, comment: "Канбан: TransferredAt. Исторические факты не удаляются."),
                    version = table.Column<long>(type: "bigint", nullable: false, comment: "Версия для optimistic concurrency. Каждое изменение увеличивает значение; stale commands отклоняются.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_kanban_memberships", x => x.id);
                    table.UniqueConstraint("ak_kanban_memberships_organization_id_property_case_id_id", x => new { x.organization_id, x.property_case_id, x.id });
                    table.ForeignKey(
                        name: "fk_kanban_memberships_organization_id_pipeline_id_stage_id",
                        columns: x => new { x.organization_id, x.pipeline_id, x.stage_id },
                        principalSchema: "procurement",
                        principalTable: "kanban_stages",
                        principalColumns: new[] { "organization_id", "pipeline_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_kanban_memberships_organization_id_property_case_id",
                        columns: x => new { x.organization_id, x.property_case_id },
                        principalSchema: "procurement",
                        principalTable: "property_cases",
                        principalColumns: new[] { "organization_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                },
                comment: "Участия PropertyCase в воронках; переданные позиции сохранены.");

            migrationBuilder.CreateTable(
                name: "kanban_tunnels",
                schema: "procurement",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Канбан: Id. Исторические факты не удаляются."),
                    organization_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Организация-владелец записи; граница изоляции доступа, устанавливаемая сервером."),
                    source_stage_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Канбан: SourceStageId. Исторические факты не удаляются."),
                    target_pipeline_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Канбан: TargetPipelineId. Исторические факты не удаляются."),
                    mode = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false, comment: "Канбан: Mode. Исторические факты не удаляются."),
                    is_active = table.Column<bool>(type: "boolean", nullable: false, comment: "Канбан: IsActive. Исторические факты не удаляются."),
                    version = table.Column<long>(type: "bigint", nullable: false, comment: "Версия для optimistic concurrency. Каждое изменение увеличивает значение; stale commands отклоняются.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_kanban_tunnels", x => x.id);
                    table.ForeignKey(
                        name: "fk_kanban_tunnels_organization_id_source_stage_id",
                        columns: x => new { x.organization_id, x.source_stage_id },
                        principalSchema: "procurement",
                        principalTable: "kanban_stages",
                        principalColumns: new[] { "organization_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_kanban_tunnels_organization_id_target_pipeline_id",
                        columns: x => new { x.organization_id, x.target_pipeline_id },
                        principalSchema: "procurement",
                        principalTable: "kanban_pipelines",
                        principalColumns: new[] { "organization_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                },
                comment: "Синхронные переходы из конечной стадии в начальную другой воронки.");

            migrationBuilder.CreateTable(
                name: "kanban_transitions",
                schema: "procurement",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Канбан: Id. Исторические факты не удаляются."),
                    organization_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Организация-владелец записи; граница изоляции доступа, устанавливаемая сервером."),
                    membership_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Канбан: MembershipId. Исторические факты не удаляются."),
                    property_case_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Самостоятельный рабочий объект закупки, к которому относится источник."),
                    from_pipeline_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "Канбан: FromPipelineId. Исторические факты не удаляются."),
                    from_stage_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "Стадия объекта непосредственно перед сохранённым переходом."),
                    to_pipeline_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Канбан: ToPipelineId. Исторические факты не удаляются."),
                    to_stage_id = table.Column<Guid>(type: "uuid", nullable: false, comment: "Стадия объекта после сохранённого перехода; не планируемая будущая стадия."),
                    from_pipeline_name = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false, comment: "Канбан: FromPipelineName. Исторические факты не удаляются."),
                    from_stage_name = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false, comment: "Канбан: FromStageName. Исторические факты не удаляются."),
                    to_pipeline_name = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false, comment: "Канбан: ToPipelineName. Исторические факты не удаляются."),
                    to_stage_name = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false, comment: "Канбан: ToStageName. Исторические факты не удаляются."),
                    recorded_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false, comment: "UTC момент записи факта в LandErp; не заменяет неизвестную дату действия факта в реальном мире."),
                    actor_employee_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "Канбан: ActorEmployeeId. Исторические факты не удаляются."),
                    command_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "Канбан: CommandId. Исторические факты не удаляются."),
                    tunnel_id = table.Column<Guid>(type: "uuid", nullable: true, comment: "Канбан: TunnelId. Исторические факты не удаляются."),
                    kind = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false, comment: "Канбан: Kind. Исторические факты не удаляются.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_kanban_transitions", x => x.id);
                    table.ForeignKey(
                        name: "fk_kanban_transitions_actor_employee_id",
                        column: x => x.actor_employee_id,
                        principalSchema: "organization",
                        principalTable: "employees",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_kanban_transitions_organization_id_property_case_id_membership_id",
                        columns: x => new { x.organization_id, x.property_case_id, x.membership_id },
                        principalSchema: "procurement",
                        principalTable: "kanban_memberships",
                        principalColumns: new[] { "organization_id", "property_case_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_kanban_transitions_organization_id_to_pipeline_id_to_stage_id",
                        columns: x => new { x.organization_id, x.to_pipeline_id, x.to_stage_id },
                        principalSchema: "procurement",
                        principalTable: "kanban_stages",
                        principalColumns: new[] { "organization_id", "pipeline_id", "id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_kanban_transitions_tunnel_id",
                        column: x => x.tunnel_id,
                        principalSchema: "procurement",
                        principalTable: "kanban_tunnels",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                },
                comment: "Неизменяемая история канбана с названиями на момент события.");

            migrationBuilder.CreateIndex(
                name: "ix_kanban_memberships_organization_id_pipeline_id_stage_id_transferred_at",
                schema: "procurement",
                table: "kanban_memberships",
                columns: new[] { "organization_id", "pipeline_id", "stage_id", "transferred_at" });

            migrationBuilder.CreateIndex(
                name: "ix_kanban_memberships_organization_id_property_case_id_pipeline_id",
                schema: "procurement",
                table: "kanban_memberships",
                columns: new[] { "organization_id", "property_case_id", "pipeline_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_kanban_pipelines_organization_id",
                schema: "procurement",
                table: "kanban_pipelines",
                column: "organization_id",
                unique: true,
                filter: "is_default AND is_active");

            migrationBuilder.CreateIndex(
                name: "ix_kanban_stages_organization_id_pipeline_id",
                schema: "procurement",
                table: "kanban_stages",
                columns: new[] { "organization_id", "pipeline_id" },
                unique: true,
                filter: "is_initial AND is_active");

            migrationBuilder.CreateIndex(
                name: "ix_kanban_transitions_actor_employee_id",
                schema: "procurement",
                table: "kanban_transitions",
                column: "actor_employee_id");

            migrationBuilder.CreateIndex(
                name: "ix_kanban_transitions_organization_id_property_case_id_membership_id",
                schema: "procurement",
                table: "kanban_transitions",
                columns: new[] { "organization_id", "property_case_id", "membership_id" });

            migrationBuilder.CreateIndex(
                name: "ix_kanban_transitions_organization_id_property_case_id_recorded_at",
                schema: "procurement",
                table: "kanban_transitions",
                columns: new[] { "organization_id", "property_case_id", "recorded_at" });

            migrationBuilder.CreateIndex(
                name: "ix_kanban_transitions_organization_id_to_pipeline_id_to_stage_id",
                schema: "procurement",
                table: "kanban_transitions",
                columns: new[] { "organization_id", "to_pipeline_id", "to_stage_id" });

            migrationBuilder.CreateIndex(
                name: "ix_kanban_transitions_tunnel_id",
                schema: "procurement",
                table: "kanban_transitions",
                column: "tunnel_id");

            migrationBuilder.CreateIndex(
                name: "ix_kanban_tunnels_organization_id_source_stage_id",
                schema: "procurement",
                table: "kanban_tunnels",
                columns: new[] { "organization_id", "source_stage_id" },
                unique: true,
                filter: "is_active");

            migrationBuilder.CreateIndex(
                name: "ix_kanban_tunnels_organization_id_target_pipeline_id",
                schema: "procurement",
                table: "kanban_tunnels",
                columns: new[] { "organization_id", "target_pipeline_id" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "kanban_transitions",
                schema: "procurement");

            migrationBuilder.DropTable(
                name: "kanban_memberships",
                schema: "procurement");

            migrationBuilder.DropTable(
                name: "kanban_tunnels",
                schema: "procurement");

            migrationBuilder.DropTable(
                name: "kanban_stages",
                schema: "procurement");

            migrationBuilder.DropTable(
                name: "kanban_pipelines",
                schema: "procurement");

            migrationBuilder.DropUniqueConstraint(
                name: "ak_property_cases_organization_id_id",
                schema: "procurement",
                table: "property_cases");
        }
    }
}

