// <auto-generated />
using System;
using LandErp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LandErp.Infrastructure.Migrations
{
    [DbContext(typeof(LandErpDbContext))]
    [Migration("20260914164026_CollectorCatalog")]
    partial class CollectorCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LandErp.Application.Modules.Catalog.Domain.CatalogObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id")
                        .HasComment("Локальное приложение Collector, которому разрешена работа или которое доставило наблюдение.");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes_json")
                        .HasComment("Поля, изменившие известное состояние; отсутствие поля не обозначает очистку.");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("content_hash")
                        .HasComment("SHA-256 typed observation для deduplication; не идентификатор объекта недвижимости.");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<string>("ObservationKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("observation_key")
                        .HasComment("Стабильный ID локального наблюдения Collector; не ExternalId объявления.");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at")
                        .HasComment("UTC момент наблюдения источника; поздняя доставка не делает старые значения новыми.");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json")
                        .HasComment("Typed public source observation: Raw/Parsed/Presence, provenance, adapter version. Не raw browser response.");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasComment("UTC момент записи факта в LandErp; не заменяет неизвестную дату действия факта в реальном мире.");

                    b.HasKey("Id")
                        .HasName("pk_observations");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_observations_job_id");

                    b.HasIndex("AgentId", "ObservationKey")
                        .IsUnique()
                        .HasDatabaseName("ix_observations_agent_id_observation_key");

                    b.HasIndex("ListingId", "ObservedAt", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_observations_listing_id_observed_at_content_hash");

                    b.ToTable("observations", "catalog", t =>
                        {
                            t.HasComment("Неизменяемые наблюдения публичных объявлений: Source/ExternalId, Raw/Parsed/Presence, provenance и версия адаптера. Browser state и raw HTML здесь не хранятся.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.Catalog.Domain.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AreaSquareMeters")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("area_square_meters")
                        .HasComment("Последняя известная площадь в м², decimal. Отсутствие не равно нулю.");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasComment("UTC момент регистрации изменения бизнес-данных; используется для очереди новых/изменившихся объектов.");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency")
                        .HasComment("ISO 4217 валюта денежного значения; Stage 1 принимает RUB.");

                    b.Property<long>("DataRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("data_revision")
                        .HasComment("Версия существенных данных объявления. Не увеличивается от неизменного повторного наблюдения.");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id")
                        .HasComment("Подразделение закупки, ограничивающее Department visibility объекта.");

                    b.Property<string>("Description")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FirstObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_observed_at")
                        .HasComment("Самый ранний известный UTC момент наблюдения этого объявления.");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at")
                        .HasComment("Самый новый принятый UTC момент наблюдения для обновления current state.");

                    b.Property<string>("Location")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("location");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id")
                        .HasComment("Организация-владелец записи; граница изоляции доступа, устанавливаемая сервером.");

                    b.Property<string>("PhotosJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("photos_json");

                    b.Property<decimal?>("Price")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("price")
                        .HasComment("Последняя известная публичная цена предложения, decimal; не подтверждённый факт сделки. Валюта отдельно.");

                    b.Property<string>("QueueReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("queue_reason")
                        .HasComment("Объяснение появления в очереди: новое объявление или реально изменённые поля.");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasComment("UTC момент записи факта в LandErp; не заменяет неизвестную дату действия факта в реальном мире.");

                    b.Property<string>("SellerName")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("seller_name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id")
                        .HasComment("Рабочая команда для Team scope. Отсутствие команды не расширяет область доступа.");

                    b.Property<string>("Title")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasComment("Версия для optimistic concurrency. Каждое изменение увеличивает значение; stale commands отклоняются.");

                    b.HasKey("Id")
                        .HasName("pk_listings");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_listings_department_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_listings_team_id");

                    b.HasIndex("OrganizationId", "ChangedAt")
                        .HasDatabaseName("ix_listings_organization_id_changed_at");

                    b.HasIndex("OrganizationId", "Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_listings_organization_id_source_external_id");

                    b.ToTable("listings", "catalog", t =>
                        {
                            t.HasComment("Текущее известное состояние объявления, не идентичность земельного участка. Отсутствие поля не стирает ранее полученное значение.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.Collection.Domain.CollectionDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id")
                        .HasComment("Локальное приложение Collector, которому разрешена работа или которое доставило наблюдение.");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("payload_hash")
                        .HasComment("SHA-256 принятого contract payload для проверки неизменности повторной доставки.");

                    b.Property<string>("ReceiptJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("receipt_json")
                        .HasComment("Прежний результат при idempotent retry, включая фактические accepted/duplicate counters.");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasComment("UTC момент записи факта в LandErp; не заменяет неизвестную дату действия факта в реальном мире.");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_deliveries_job_id");

                    b.ToTable("deliveries", "collection", t =>
                        {
                            t.HasComment("Неизменяемые квитанции доставки Collector. Повтор ResultId с тем же payload возвращает прежний ответ; другой payload запрещён.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.Collection.Domain.CollectorAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("capabilities")
                        .HasComment("Источники, которые поддерживает установленная версия Collector; неподдерживаемая работа не выдаётся.");

                    b.Property<string>("CredentialHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("credential_hash")
                        .HasComment("SHA-256 verifier высокоэнтропийного credential Collector. Открытый token показывается только при создании.");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at")
                        .HasComment("Последний принятый heartbeat UTC; online означает enabled и связь не старше трёх минут.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id")
                        .HasComment("Организация-владелец записи; граница изоляции доступа, устанавливаемая сервером.");

                    b.Property<DateTimeOffset?>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasComment("Версия для optimistic concurrency. Каждое изменение увеличивает значение; stale commands отклоняются.");

                    b.Property<string>("VersionText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("version_text")
                        .HasComment("Версия установленного приложения Collector; не concurrency token.");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_agents_organization_id");

                    b.ToTable("agents", "collection", t =>
                        {
                            t.HasComment("Зарегистрированные локальные Collector. Сервер хранит только verifier credential; отзыв немедленно запрещает новые обращения.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.Collection.Domain.SearchConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id")
                        .HasComment("Локальное приложение Collector, которому разрешена работа или которое доставило наблюдение.");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id")
                        .HasComment("Подразделение закупки, ограничивающее Department visibility объекта.");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("label");

                    b.Property<int>("MaxPages")
                        .HasColumnType("integer")
                        .HasColumnName("max_pages");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id")
                        .HasComment("Организация-владелец записи; граница изоляции доступа, устанавливаемая сервером.");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id")
                        .HasComment("Рабочая команда для Team scope. Отсутствие команды не расширяет область доступа.");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasComment("Версия для optimistic concurrency. Каждое изменение увеличивает значение; stale commands отклоняются.");

                    b.HasKey("Id")
                        .HasName("pk_search_configurations");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_search_configurations_agent_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_search_configurations_department_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_search_configurations_team_id");

                    b.ToTable("search_configurations", "collection", t =>
                        {
                            t.HasComment("Разрешённые поиски организации с конкретным Collector и областью закупки. Browser settings и cookies остаются локально.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.Collection.Domain.ServerCollectionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("integer")
                        .HasColumnName("accepted_count");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id")
                        .HasComment("Локальное приложение Collector, которому разрешена работа или которое доставило наблюдение.");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at")
                        .HasComment("UTC срок действия reservation; heartbeat продлевает только действующий lease.");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id")
                        .HasComment("Случайный fencing token конкретной выдачи работы; прежний token после перевыдачи отклоняется.");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id")
                        .HasComment("Организация-владелец записи; граница изоляции доступа, устанавливаемая сервером.");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("result_code");

                    b.Property<Guid>("SearchId")
                        .HasColumnType("uuid")
                        .HasColumnName("search_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state")
                        .HasComment("Состояние работы: Pending ожидает выдачи; Leased действует до LeaseExpiresAt; Completed/LimitReached завершены; ручная проверка/ошибка/прерывание не являются успешной пустой выдачей.");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasComment("Версия для optimistic concurrency. Каждое изменение увеличивает значение; stale commands отклоняются.");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_jobs_agent_id");

                    b.HasIndex("SearchId", "State")
                        .HasDatabaseName("ix_jobs_search_id_state");

                    b.ToTable("jobs", "collection", t =>
                        {
                            t.HasComment("Одна работа сбора: Pending ожидает; Leased закреплена до срока; Completed/LimitReached завершена; AwaitingManualAction требует ручного действия; Failed/Interrupted не считаются пустым успехом.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.IdentityAccess.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("action")
                        .HasComment("Стабильный код выполненного значимого действия, история сохраняется append-only.");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id")
                        .HasComment("Автор действия — доверенная серверная идентичность; не берётся из клиентского payload.");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes")
                        .HasComment("Безопасные значения значимых изменений до/после в JSON; passwords, cookies, tokens и ключи исключены.");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("correlation_id")
                        .HasComment("Ограниченный безопасный идентификатор связи действия с HTTP-запросом или локальной командой.");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_id")
                        .HasComment("Внутренний UUID бизнес-объекта, к которому относится событие.");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_type")
                        .HasComment("Тип связанного бизнес-объекта, позволяющий восстановить происхождение действия.");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id")
                        .HasComment("Организация-владелец записи; граница изоляции доступа, устанавливаемая сервером.");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasComment("UTC момент записи факта в LandErp; не заменяет неизвестную дату действия факта в реальном мире.");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.ToTable("audit_events", "foundation", t =>
                        {
                            t.HasComment("Неизменяемый журнал значимых действий: кто, когда, что и в какой области изменил. Runtime не исправляет и не удаляет события.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.IdentityAccess.Domain.EmployeeInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at")
                        .HasComment("UTC момент однократной активации. Непустое значение запрещает повторное использование.");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id")
                        .HasComment("Сотрудник, к которому относится назначение или приглашение.");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at")
                        .HasComment("UTC момент окончания действия приглашения; после него активация запрещена.");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash")
                        .HasComment("SHA-256 одноразового высокоэнтропийного token; открытое значение не хранится.");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasComment("Версия для optimistic concurrency. Каждое изменение увеличивает значение; stale commands отклоняются.");

                    b.HasKey("Id")
                        .HasName("pk_employee_invitations");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_invitations_employee_id");

                    b.ToTable("employee_invitations", "identity", t =>
                        {
                            t.HasComment("Одноразовые приглашения для активации сотрудников; открытый token не сохраняется, повторное использование запрещено.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.IdentityAccess.Domain.PermissionDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "identity", t =>
                        {
                            t.HasComment("Каталог стабильных системных разрешений на действия. Проверяется сервером вместе с scope.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.IdentityAccess.Domain.RolePermissionGrant", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasComment("Набор permissions для текущего назначения; итоговый доступ ограничен scope.");

                    b.Property<string>("PermissionId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("permission_id")
                        .HasComment("Стабильный код серверной проверки операции, а не название кнопки интерфейса.");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", "identity", t =>
                        {
                            t.HasComment("Состав разрешений каждой роли. Не даёт доступ к другим организациям.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.Organization.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active")
                        .HasComment("Разрешена ли работа сотрудника. При выключении существующая cookie не обходит серверную проверку.");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id")
                        .HasComment("Организация-владелец записи; граница изоляции доступа, устанавливаемая сервером.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Связь с технической учётной записью; не является внешним ID или бизнес-номером.");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasComment("Версия для optimistic concurrency. Каждое изменение увеличивает значение; stale commands отклоняются.");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_employees_organization_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_user_id");

                    b.ToTable("employees", "organization", t =>
                        {
                            t.HasComment("Профили сотрудников организации, связанные с учётной записью. Неактивный сотрудник не получает бизнес-доступ.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.Organization.Domain.EmployeeAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id")
                        .HasComment("Сотрудник, к которому относится назначение или приглашение.");

                    b.Property<Guid?>("ManagerEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_employee_id")
                        .HasComment("Руководитель сотрудника, которому можно передать рабочую ответственность.");

                    b.Property<Guid?>("OrgUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_unit_id")
                        .HasComment("Подразделение рабочей ответственности; используется для Department scope.");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id")
                        .HasComment("Должность в организации; права определяются отдельно через роль и permission.");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasComment("Набор permissions для текущего назначения; итоговый доступ ограничен scope.");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope")
                        .HasComment("Own — собственные записи; AssignedObjects — назначенные объекты; Team — команда; Department — подразделение; Organization — одна организация.");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id")
                        .HasComment("Рабочая команда для Team scope. Отсутствие команды не расширяет область доступа.");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasComment("Версия для optimistic concurrency. Каждое изменение увеличивает значение; stale commands отклоняются.");

                    b.HasKey("Id")
                        .HasName("pk_employee_assignments");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_assignments_employee_id");

                    b.HasIndex("ManagerEmployeeId")
                        .HasDatabaseName("ix_employee_assignments_manager_employee_id");

                    b.HasIndex("OrgUnitId")
                        .HasDatabaseName("ix_employee_assignments_org_unit_id");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_employee_assignments_position_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_employee_assignments_role_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_employee_assignments_team_id");

                    b.ToTable("employee_assignments", "organization", t =>
                        {
                            t.HasComment("Актуальное назначение сотрудника: подразделение, должность, команда, руководитель и роль с областью доступа.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.Organization.Domain.OrgUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id")
                        .HasComment("Организация-владелец записи; граница изоляции доступа, устанавливаемая сервером.");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasComment("Версия для optimistic concurrency. Каждое изменение увеличивает значение; stale commands отклоняются.");

                    b.HasKey("Id")
                        .HasName("pk_org_units");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_org_units_organization_id_name");

                    b.ToTable("org_units", "organization", t =>
                        {
                            t.HasComment("Подразделения организации, определяющие рабочую ответственность и Department visibility.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.Organization.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessTimeZone")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("business_time_zone")
                        .HasComment("Явный IANA timezone бизнес-сроков организации. Instants в БД сохраняются UTC.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", "organization", t =>
                        {
                            t.HasComment("Организации, являющиеся границами доступа LandErp. Не являются юридическими лицами сделки.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.Organization.Domain.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id")
                        .HasComment("Организация-владелец записи; граница изоляции доступа, устанавливаемая сервером.");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasComment("Версия для optimistic concurrency. Каждое изменение увеличивает значение; stale commands отклоняются.");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_positions_organization_id_name");

                    b.ToTable("positions", "organization", t =>
                        {
                            t.HasComment("Настраиваемые должности сотрудников; название должности само по себе не предоставляет permissions.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.Organization.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_unit_id")
                        .HasComment("Подразделение рабочей ответственности; используется для Department scope.");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id")
                        .HasComment("Организация-владелец записи; граница изоляции доступа, устанавливаемая сервером.");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_teams_organization_id");

                    b.HasIndex("OrgUnitId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_org_unit_id_name");

                    b.ToTable("teams", "organization", t =>
                        {
                            t.HasComment("Рабочие команды внутри подразделения; используются для Team visibility.");
                        });
                });

            modelBuilder.Entity("LandErp.Infrastructure.Modules.IdentityAccess.LandErpUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count")
                        .HasComment("Число неуспешных попыток, используемое Identity lockout policy.");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("concurrency_stamp")
                        .HasComment("Технический Identity concurrency token для защиты от потерянных обновлений.");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed")
                        .HasComment("Адрес активирован закрытым приглашением или локальным Owner bootstrap; публичной регистрации нет.");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end")
                        .HasComment("UTC момент завершения блокировки входа после неуспешных попыток.");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash")
                        .HasComment("Identity password verifier; открытый пароль не хранится и не логируется.");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("security_stamp")
                        .HasComment("Версия безопасности Identity для отзыва сессий при изменении учётной записи.");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled")
                        .HasComment("Включена MFA. Для Owner/Administrator этого поля недостаточно: текущий вход также должен пройти MFA.");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_user_name");

                    b.ToTable("users", "identity", t =>
                        {
                            t.HasComment("Учётные записи сотрудников. Пароли хранятся только как Identity verifier; доступ к бизнес-данным задаётся назначениями и permissions.");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("concurrency_stamp")
                        .HasComment("Технический Identity concurrency token для защиты от потерянных обновлений.");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_normalized_name");

                    b.ToTable("roles", "identity", t =>
                        {
                            t.HasComment("Именованные наборы разрешений. Роль не заменяет проверку области данных.");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasComment("Набор permissions для текущего назначения; итоговый доступ ограничен scope.");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", "identity", t =>
                        {
                            t.HasComment("Технические утверждения ролей Identity; бизнес permissions хранятся отдельно.");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Связь с технической учётной записью; не является внешним ID или бизнес-номером.");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", "identity", t =>
                        {
                            t.HasComment("Технические утверждения Identity. OrganizationId из клиентского payload не считается доказательством доступа.");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Связь с технической учётной записью; не является внешним ID или бизнес-номером.");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", "identity", t =>
                        {
                            t.HasComment("Технические связи с провайдерами входа Identity. В Stage 1 внешние провайдеры не включены.");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Связь с технической учётной записью; не является внешним ID или бизнес-номером.");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasComment("Набор permissions для текущего назначения; итоговый доступ ограничен scope.");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "identity", t =>
                        {
                            t.HasComment("Технические роли Identity для требований MFA и управления сессией. Бизнес-доступ проверяется по актуальному назначению сотрудника.");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Связь с технической учётной записью; не является внешним ID или бизнес-номером.");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("value")
                        .HasComment("Техническое значение Identity token или claim. Секретные token values не публикуются и не входят в аудит.");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", "identity", t =>
                        {
                            t.HasComment("Технические секреты и verifier Identity, включая ключ MFA. Не выводятся в UI журналов, логи и аудит.");
                        });
                });

            modelBuilder.Entity("LandErp.Application.Modules.Catalog.Domain.CatalogObservation", b =>
                {
                    b.HasOne("LandErp.Application.Modules.Collection.Domain.CollectorAgent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observations_agent_id");

                    b.HasOne("LandErp.Application.Modules.Collection.Domain.ServerCollectionJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observations_job_id");

                    b.HasOne("LandErp.Application.Modules.Catalog.Domain.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observations_listing_id");
                });

            modelBuilder.Entity("LandErp.Application.Modules.Catalog.Domain.Listing", b =>
                {
                    b.HasOne("LandErp.Application.Modules.Organization.Domain.OrgUnit", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_listings_department_id");

                    b.HasOne("LandErp.Application.Modules.Organization.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_listings_organization_id");

                    b.HasOne("LandErp.Application.Modules.Organization.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_listings_team_id");
                });

            modelBuilder.Entity("LandErp.Application.Modules.Collection.Domain.CollectionDelivery", b =>
                {
                    b.HasOne("LandErp.Application.Modules.Collection.Domain.ServerCollectionJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deliveries_job_id");
                });

            modelBuilder.Entity("LandErp.Application.Modules.Collection.Domain.CollectorAgent", b =>
                {
                    b.HasOne("LandErp.Application.Modules.Organization.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agents_organization_id");
                });

            modelBuilder.Entity("LandErp.Application.Modules.Collection.Domain.SearchConfiguration", b =>
                {
                    b.HasOne("LandErp.Application.Modules.Collection.Domain.CollectorAgent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_search_configurations_agent_id");

                    b.HasOne("LandErp.Application.Modules.Organization.Domain.OrgUnit", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_search_configurations_department_id");

                    b.HasOne("LandErp.Application.Modules.Organization.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_search_configurations_team_id");
                });

            modelBuilder.Entity("LandErp.Application.Modules.Collection.Domain.ServerCollectionJob", b =>
                {
                    b.HasOne("LandErp.Application.Modules.Collection.Domain.CollectorAgent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_agent_id");

                    b.HasOne("LandErp.Application.Modules.Collection.Domain.SearchConfiguration", null)
                        .WithMany()
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_search_id");
                });

            modelBuilder.Entity("LandErp.Application.Modules.IdentityAccess.Domain.EmployeeInvitation", b =>
                {
                    b.HasOne("LandErp.Application.Modules.Organization.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_invitations_employee_id");
                });

            modelBuilder.Entity("LandErp.Application.Modules.IdentityAccess.Domain.RolePermissionGrant", b =>
                {
                    b.HasOne("LandErp.Application.Modules.IdentityAccess.Domain.PermissionDefinition", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permission_id");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_role_id");
                });

            modelBuilder.Entity("LandErp.Application.Modules.Organization.Domain.Employee", b =>
                {
                    b.HasOne("LandErp.Application.Modules.Organization.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_organization_id");

                    b.HasOne("LandErp.Infrastructure.Modules.IdentityAccess.LandErpUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_user_id");
                });

            modelBuilder.Entity("LandErp.Application.Modules.Organization.Domain.EmployeeAssignment", b =>
                {
                    b.HasOne("LandErp.Application.Modules.Organization.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_assignments_employee_id");

                    b.HasOne("LandErp.Application.Modules.Organization.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_employee_assignments_manager_employee_id");

                    b.HasOne("LandErp.Application.Modules.Organization.Domain.OrgUnit", null)
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_employee_assignments_org_unit_id");

                    b.HasOne("LandErp.Application.Modules.Organization.Domain.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_employee_assignments_position_id");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_assignments_role_id");

                    b.HasOne("LandErp.Application.Modules.Organization.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_employee_assignments_team_id");
                });

            modelBuilder.Entity("LandErp.Application.Modules.Organization.Domain.OrgUnit", b =>
                {
                    b.HasOne("LandErp.Application.Modules.Organization.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_org_units_organization_id");
                });

            modelBuilder.Entity("LandErp.Application.Modules.Organization.Domain.Position", b =>
                {
                    b.HasOne("LandErp.Application.Modules.Organization.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_organization_id");
                });

            modelBuilder.Entity("LandErp.Application.Modules.Organization.Domain.Team", b =>
                {
                    b.HasOne("LandErp.Application.Modules.Organization.Domain.OrgUnit", null)
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teams_org_unit_id");

                    b.HasOne("LandErp.Application.Modules.Organization.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teams_organization_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("LandErp.Infrastructure.Modules.IdentityAccess.LandErpUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("LandErp.Infrastructure.Modules.IdentityAccess.LandErpUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_role_id");

                    b.HasOne("LandErp.Infrastructure.Modules.IdentityAccess.LandErpUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("LandErp.Infrastructure.Modules.IdentityAccess.LandErpUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
