<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" PrivateAssets="all" />
    <PackageReference Include="MSTest.TestFramework" PrivateAssets="all" />
    <PackageReference Include="MSTest.TestAdapter" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Playwright" PrivateAssets="all" />
    <ProjectReference Include="../../src/LandErp.Application/LandErp.Application.csproj" />
    <ProjectReference Include="../../src/LandErp.Infrastructure/LandErp.Infrastructure.csproj" />
    <ProjectReference Include="../../src/LandErp.Server/LandErp.Server.csproj" />
    <ProjectReference Include="../../src/LandErp.Worker/LandErp.Worker.csproj" />
  </ItemGroup>
</Project>
